use_frameworks!

platform :ios, '11.0'

target 'GXPKHUD_Example' do
  pod 'GXPKHUD', :path => '../'

  target 'GXPKHUD_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
